# Generated by Django 5.2 on 2025-12-26 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='core.country')),
            ],
            options={
                'unique_together': {('country', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('hotel', 'Hotel'), ('cafe', 'Cafe'), ('attraction', 'Attraction'), ('nature', 'Nature'), ('coworking', 'Coworking'), ('restaurant', 'Restaurant')], max_length=20)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('maps_url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='core.city')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_or_bad', models.CharField(choices=[('good', 'Good'), ('bad', 'Bad')], max_length=10)),
                ('elderly_score', models.PositiveSmallIntegerField(default=3)),
                ('young_score', models.PositiveSmallIntegerField(default=3)),
                ('work_score', models.PositiveSmallIntegerField(default=3)),
                ('nature_score', models.PositiveSmallIntegerField(default=3)),
                ('comment', models.TextField(blank=True)),
                ('place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='core.place')),
            ],
        ),
    ]
