# Generated by Django 5.2 on 2025-12-27 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_place_google_place_id_place_latitude_place_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='category',
            field=models.CharField(choices=[('hotel', 'Hotel'), ('restaurant', 'Restaurant'), ('cafe', 'Coffee'), ('mountain', 'Mountain'), ('nature', 'Nature'), ('attraction', 'Attraction'), ('coworking', 'Coworking')], max_length=20),
        ),
    ]
